import type { Metadata } from "next";
import { DefaultSeo } from 'next-seo';
import { AppShell, ColorSchemeScript, MantineProvider } from "@mantine/core";
import Head from "next/head";
import { Analytics } from "@vercel/analytics/react"
import { Work_Sans } from 'next/font/google'

import '@mantine/core/styles.css';
import '@mantine/carousel/styles.css';
import "./globals.scss";

const workSans = Work_Sans({
  subsets: ['latin'],
  display: 'swap',
  weight: ["400", "600"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <DefaultSeo
        title="Next SEO Example"
        description="Next SEO is a plug in that makes managing your SEO easier in Next.js projects."
        openGraph={{
          type: 'website',
          locale: 'en_IE',
          url: 'https://www.url.ie/',
          siteName: 'SiteName',
        }}
        twitter={{
          handle: '@handle',
          site: '@site',
          cardType: 'summary_large_image',
        }}
      />
      <body className={`${workSans.className}`}>
        <ColorSchemeScript />
        <MantineProvider>
          <Analytics />
          <AppShell>
            <main>
              {children}
            </main>
          </AppShell>
        </MantineProvider>
      </body>
    </html>
  );
}
